version: '3.8'

services:
  webserver:
    build: .
    container_name: nginx-curl-server
    environment:
      - SCANNER_BD_HOST=${SCANNER_BD_HOST:-192.168.0.166}
      - SCANNER_BD_PORT=${SCANNER_BD_PORT:-8080}
      - SCANNER_69_HOST=${SCANNER_69_HOST:-192.168.0.166}
      - SCANNER_69_PORT=${SCANNER_69_PORT:-8081}
    ports:
      - "${HOST_PORT:-80}:80"
    volumes:
      - nginx_html:/usr/share/nginx/html
      - nginx_config:/usr/local/openresty/nginx/conf/custom
    restart: unless-stopped

volumes:
  nginx_html:
    driver_opts:
      type: nfs
      device: ":/Docker/nginx-curl/html"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
  nginx_config:
    driver_opts:
      type: nfs
      device: ":/Docker/nginx-curl/config"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
