version: '3.8'

services:
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    container_name: simple-webserver
